# This file defines the cameras in the system
cameras:
    rgbd: 
        type: realsense_d435i
        quantity: 1
        
    tof:
        type: vl6180
        quantity: 2
        
    
    
    
    
    