name: pybullet-tree-sim-workflow

on: 
    pull_request:
        branches: ['main', 'develop']

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
              with:
                  options: "--check --verbose --diff --line-length=120 ./"