name: pybullet-tree-sim-workflow

on:
    pull_request:
        branches: ['main', 'develop']

jobs:
    # lint:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - uses: psf/black@stable
    #           with:
    #               options: "--check --verbose --diff --line-length=120 ./"
    build:
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.8, 3.9, 3.10]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install .
                pip install flake8 black pytest
            - name: Format with black
              uses: psf/black@stable
              with:
                  python-version: ${{ matrix.python-version }}
                  options: "--check --verbose --diff --line-length=120 ./"
